-- Add collected_params column to workflows table
-- This column stores parameters collected during the chat workflow completion process

ALTER TABLE workflows
ADD COLUMN IF NOT EXISTS collected_params JSONB DEFAULT '{}'::jsonb;

-- Add missing_info column to store what information is needed
ALTER TABLE workflows
ADD COLUMN IF NOT EXISTS missing_info JSONB DEFAULT '[]'::jsonb;

-- Add comment
COMMENT ON COLUMN workflows.collected_params IS 'Parameters collected from user during chat workflow completion';
COMMENT ON COLUMN workflows.missing_info IS 'Information needed to complete the workflow (generated by LLM)';
